### ISSUE TITLE
Missed slash in section 3-chroot/013a-zlib-ng

### ISSUE THREAD

**Issue by Cerberios** [dslm4515/CMLFS#61]
Stage 3-chroot/013a-zlib-ng: seems mises "/" symbol

**Comment by Cerberios** [comment]
Section 3-chroot/013a-zlib-ng

# Move pkconfig to correct location:
**mv lib/pkgconfig/* /usr/lib/pkgconfig/**

Actual: mv lib/..... But we still INSIDE zlib-ng folder, so need set start from root  and seems missed slash - /
Expected: *  *mv /lib/pkgconfig/* /usr/lib/pkgconfig/*  *

And smth wrong with pkgconfig...Before stage 3-chroot/013a-zlib-ng it was as file, but should be as directory with .pc files inside. I'll recheck where it fall and report later.

BTW, Derek - why there so huge amount of bugs occur? They ALL are critical because it is cross-process, each wrong symbol  can broke whole system. Did You tested this manual? I going step by step and will report more. Idea is super good - I'd like to complete with live Cinnamon Desktop + Firefox + Thunderbirg and LUKS for whole disk. Alot of work need to do ) Will report more

**Comment by dslm4515** [comment]
>...Move pkconfig to correct location:
** mv lib/pkgconfig/* /usr/lib/pkgconfig/ **

This can be fixed by running the `configure` script like this:
```
./configure  --prefix=/usr \
             --libdir=/usr/lib \
             --zlib-compat \
             --sharedlibdir=/usr/lib 
```
_This should put the pkgconfig files in the correct directory_

**Comment by dslm4515** [comment]
>BTW, Derek - why there so huge amount of bugs occur? They ALL are critical because it is cross-process, each wrong symbol can broke whole system. Did You tested this manual?

Correction: Derrick, not _Derek_ ... You can also just use @dslm4515 instead

I did not document every command during my last build of CMLFS because I was in a hurry to see what issues would zlib-ng would cause [when building more packages outside of CMLFS]. I know for sure, Perl does not support zlib-ng. Workaround is to compile perl with its bundled source copy of zlib.

Additionally, I need to go through another build of CMLFS as I will changing a few things:

- Drop use of obsolete `bin` user and group
- Unify `/bin`, `/sbin`, and `/lib` with counterparts in `/usr` via symbolic links 
- Replacing ncurses with netbsd-curses. So far `htop` does not build with it

_This is a hobby, not a job. The "manual' for building [LFS](https://www.linuxfromscratch.org/) is managed by 6 people. I am one person updating 4 other repositories like this one. So there will be typos. Some repos may not have the updates from the other repo(s) yet. I work full time and work on these repos during my breaks at work._

_CMLFS was very difficult  to get started and took many many attempts to the point I stopped documenting to save on time._

**Comment by dslm4515** [comment]
>I'd like to complete with live Cinnamon Desktop + Firefox + Thunderbirg and LUKS for whole disk

As a heads up. I do not use Cinnamon Desktop, _Thunderbird_ and LUKS... therefore, I have no experience in building those or troubleshooting those.

I haven't built Firefox from source for quite some time for two reasons:

- Rust keeps failing to build on musl. Errors fall into two categories: Syntax errors (even when compiling rust with the same rust version pre-compiled from Alpine Linux) and cryptic build errors that have little or no documentation.
- I cannot find reliable patches to remove dependencies on Xorg. Firefox source still expects GTK3+ to be built with Xorg support. Yes, technically, Firefox (pre-compiled from Alpine Linux) can run in wayland, but still checks for unused dependencies on Xorg libraries. _I am trying to avoid building Xorg because of the high number of packages built AND its old, carrying a lot of deprecated code I will never use_

**Comment by Cerberios** [comment]
Thank You for clarification, I am totally agree. I tried to compile Rust 1.57 under some "stage3 ready  clang without GCC at all" image, seems it working, but some problems with Spidermonkey was occur. Anyway, Firefox not a point, I can use Palemoon also (just better choice IMO): GTK 2.24 or GTK 3.22+ (Not GTK 4) ; GLib 2.22 or higher ; Pango 1.14 or higher ; libstdc++ 4.6.1 or higher ( more info - https://developer.palemoon.org/build/linux/ )

**Comment by dslm4515** [comment]
> I can use Palemoon also (just better choice IMO)

I have built Palemoon years ago on i686 when I couldn't build rust or use rust from Alpine (mismatched LLVM version, missing symbols)... I forgot why I don't use it... unless it's because Palemoon requires GTK+2 which requires X11 libraries.

**Comment by dslm4515** [comment]
closing ... typo has been fixed.
